Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/bacid/文档/code/10.5/build/CMakeFiles/CMakeScratch/TryCompile-VRadpM

Run Build Command(s):/usr/bin/make -f Makefile cmTC_4c226/fast && /usr/bin/make  -f CMakeFiles/cmTC_4c226.dir/build.make CMakeFiles/cmTC_4c226.dir/build
make[1]: 进入目录“/home/bacid/文档/code/10.5/build/CMakeFiles/CMakeScratch/TryCompile-VRadpM”
Building C object CMakeFiles/cmTC_4c226.dir/src.c.o
/usr/bin/gcc -DCMAKE_HAVE_LIBC_PTHREAD  -fPIC  -o CMakeFiles/cmTC_4c226.dir/src.c.o -c /home/bacid/文档/code/10.5/build/CMakeFiles/CMakeScratch/TryCompile-VRadpM/src.c
Linking C executable cmTC_4c226
/home/bacid/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4c226.dir/link.txt --verbose=1
/usr/bin/gcc -fPIC  CMakeFiles/cmTC_4c226.dir/src.c.o -o cmTC_4c226 
/usr/bin/ld: CMakeFiles/cmTC_4c226.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x5e): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x6f): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_4c226.dir/build.make:99：cmTC_4c226] 错误 1
make[1]: 离开目录“/home/bacid/文档/code/10.5/build/CMakeFiles/CMakeScratch/TryCompile-VRadpM”
make: *** [Makefile:127：cmTC_4c226/fast] 错误 2


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}


Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/bacid/文档/code/10.5/build/CMakeFiles/CMakeScratch/TryCompile-vC73XI

Run Build Command(s):/usr/bin/make -f Makefile cmTC_9dba2/fast && /usr/bin/make  -f CMakeFiles/cmTC_9dba2.dir/build.make CMakeFiles/cmTC_9dba2.dir/build
make[1]: 进入目录“/home/bacid/文档/code/10.5/build/CMakeFiles/CMakeScratch/TryCompile-vC73XI”
Building C object CMakeFiles/cmTC_9dba2.dir/CheckFunctionExists.c.o
/usr/bin/gcc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_9dba2.dir/CheckFunctionExists.c.o -c /home/bacid/文档/code/10.5/build/CMakeFiles/CMakeScratch/TryCompile-vC73XI/CheckFunctionExists.c
Linking C executable cmTC_9dba2
/home/bacid/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9dba2.dir/link.txt --verbose=1
/usr/bin/gcc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_9dba2.dir/CheckFunctionExists.c.o -o cmTC_9dba2  -lpthreads 
/usr/bin/ld: 找不到 -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_9dba2.dir/build.make:99：cmTC_9dba2] 错误 1
make[1]: 离开目录“/home/bacid/文档/code/10.5/build/CMakeFiles/CMakeScratch/TryCompile-vC73XI”
make: *** [Makefile:127：cmTC_9dba2/fast] 错误 2



